### ISSUE TITLE
Multiple user IDs registered under the same email address

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#109] opened 2020-07-04 13:46 UTC
It seems the platform currently allows multiple users to be registered using the same email address? I am able to create two accounts (ks709, and ks7099) using the same email address - should we disable this?

**Comment by sou-chon** [comment] 2020-07-05 17:03
This is set up to be handled by the mongodb by setting a unique constraint. Not the app itself. The app is responsible for relaying (and possibly formatting) the error message from mongodb.

This should be set up automatically if you run the setup up script:

https://github.com/ideafast/ideafast-portal/blob/76641e49e75866b3acdfa2faf0d242ffa535a650/packages/itmat-utils/src/databaseSetup/collectionsAndIndexes.ts#L12-L19


This script has been moved to itmat-setup package in the itmat-broker repo:
https://github.com/dsi-icl/itmat-broker/blob/fdc05ea3bee50ba1e3c5da7e35ba07554005af88/packages/itmat-setup/src/databaseSetup/collectionsAndIndexes.ts#L12-L19

**Comment by sou-chon** [comment] 2020-07-05 17:15
dup #100 

I suggest adding a email check here in the line that @wsy19961129 quoted. To avoid doing bcrypt if unneeded.

**Comment by fguitton** [comment] 2020-07-07 11:22
I suppose since the issue is one of database configuration this won't be fixed as such at this point in time. The IDEAFAST db has now been configured with those indexes. We might want to track another issue to add feature that analyse DB structure and makes sure system operates according to plans.

**Closed by fguitton** 2020-07-07 11:22 UTC
Labels: WP5, wontfix
